mongoDb:
    url: mongodb://ws1:27017
---
spring:
    profiles: dev
mongoDb:
    url: mongodb://ws1:27017
dataFileRoot: D:/Dev/nbnMonitor/share/output
---
spring:
    profiles: production
mongoDb:
    url: mongodb://localhost:27017
    
