
require_relative 'localConfig.rb'
include LOCAL_CONFIG
hostDevDir = HOST_DEV_DIR

Vagrant.configure("2") do |config|
  config.vm.box = "Bassualdo/raspberryDesktop"
  config.vm.box_version = "1.0.0"
  
  config.vm.network "private_network", ip: "192.170.1.5"
  config.vm.network "forwarded_port", guest: 22, host: 2225, id: "ssh", auto_correct: true
  config.vm.network "forwarded_port", guest: 8080, host: 28085, id: "ssh", auto_correct: true
  config.vm.network "forwarded_port", guest: 27017, host: 28017, id: "ssh", auto_correct: true

# Note to get the 'vagrant up'  command to complete the password to the pi account must be set to the below.
  config.ssh.username = "pi"
  config.ssh.password = "vagrant"
  
  config.vm.boot_timeout = 200

  config.vm.synced_folder "#{hostDevDir}/share", "/home/pi/monitorNbn/share", type: "virtualbox"
  config.vm.synced_folder ".", "/vagrant", disabled: true

  config.vm.provider "virtualbox" do |vb|
    vb.name = "RaspberryPi"
    # Display the VirtualBox GUI when booting the machine
    vb.gui = true
  
    # Customize the amount of memory on the VM:
    vb.memory = "2048"
    vb.cpus = 4
    vb.customize ["modifyvm", :id, "--vram", "16"]
    vb.customize ["modifyvm", :id, "--clipboard-mode", "bidirectional"]
    vb.customize ["modifyvm", :id, "--draganddrop", "bidirectional"]
	
  end

# sudo mount -t vboxsf -o uid=1000,gid=1000 share ~/host
# sudo mount -t vboxsf -o uid=1000,gid=1000 share /home/pi/monitorNbn/share
  
end


